name: Deploy CI
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    name: Build files
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: ":rocket: Deploy new version [skip ci]"
          commit_user_name: BetaHuhn Bot
          commit_user_email: bot@mxis.ch
          commit_author: BetaHuhn Bot <bot@mxis.ch>